version: "1"
services:
  - type: web
    name: sokoni-connect-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: sokoni-connect-render-secret-2024
      - key: PORT
        value: 5000
